tasks:
  - init: 
      pip install -r requirements.txt 
      export FLASK_RUN_PORT=0.0.0.0
      export FLASK_RUN_HOST=8080
      export FLASK_ENV=development
      
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addCheck: true
    addComment: false